eventex/core/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.core.views',
    url(r'^$', 'home', name='home'),
    url(r'^palestrantes/(?P<slug>[\w-]+)/$', 'speaker_detail', name='speaker_detail'),
    url(r'^palestras/$', 'talk_list', name='talk_list'),
    url(r'^palestras/(?P<pk>\d+)/$', 'talk_detail', name='talk_detail'),
)

eventex/subscriptions/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('eventex.subscriptions.views', 
    url(r'^$', 'subscribe', name='subscribe'),
    url(r'^(\d+)/$', 'detail', name='detail'),
)

eventex/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^inscricao/', include('eventex.subscriptions.urls', namespace='subscriptions')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('eventex.core.urls', namespace='core')),
)

eventex/core/models.py
# coding: utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _
from eventex.core.managers import KindContactManager, PeriodManager
from django.db.models.base import Model

# Create your models here.
class Speaker(models.Model):
    name = models.CharField(_('Nome'), max_length=255)
    slug = models.SlugField(_('Slug'))
    url = models.URLField(_('Url'))
    description = models.TextField(_(u'Descrição'), blank=True)

    def __unicode__(self):
        return self.name
    
    @models.permalink
    def get_absolute_url(self):
        return ('core:speaker_detail', (), {'slug': self.slug})
    
class Contact(models.Model):
    KINDS = (
            ('P', _('Telefone')),
            ('E', _('E-mail')),
            ('F', _('Fax')),
             )

    speaker = models.ForeignKey('Speaker', verbose_name=_('Palestrante'))
    kind = models.CharField(_('tipo'), max_length=1, choices=KINDS)
    value = models.CharField(_('valor'), max_length=255)

    objects = models.Manager()
    emails = KindContactManager('E')
    phones = KindContactManager('P')
    faxes = KindContactManager('F')

    def __unicode__(self):
        return self.value
    
class Talk(models.Model):
    title = models.CharField(_(u'Título'), max_length=200)
    description = models.TextField(_(u'Descrição'))
    start_time = models.TimeField(_(u'Horário'), blank=True)
    speakers = models.ManyToManyField('Speaker', verbose_name=_('palestrantes'))
    
    objects = PeriodManager()
    
    class Meta:
        verbose_name = _('palestra')
        verbose_name_plural = _('palestras')
    
    def __unicode__(self):
        return self.title
    
    @models.permalink
    def get_absolute_url(self):
        return ('core:talk_detail', (), {'pk': self.pk})
    
    @property
    def slides(self):
        return self.media_set.filter(kind='SL')
    
    @property
    def videos(self):
        return self.media_set.filter(kind='YT')
    
    

class Course(Talk):
    slots = models.IntegerField(_('vagas'))
    notes = models.TextField(_(u'observações'))
    
    objects = PeriodManager()
    
class Media(models.Model):
    MEDIAS = (
              ('YT', _('YouTube')),
              ('SL', _('SlideShare'))
              )
    
    talk = models.ForeignKey('Talk', verbose_name = _('palestra'))
    kind = models.CharField(_('tipo'), max_length=2, choices=MEDIAS)
    title = models.CharField(_(u'Título'), max_length=255)
    media_id = models.CharField(_('ref'), max_length=255)
    
    def __unicode__(self):
        return u'%s - %s' % (self.talk.title, self.title)
    
    
    
    
    
    
    
    
    
    

eventex/core/views.py
# coding: utf-8
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from eventex.core.models import Speaker, Talk

def home(request):
    return render(request, 'index.html')

def speaker_detail(request, slug):
    speaker = get_object_or_404(Speaker, slug=slug)
    context = {'speaker': speaker}
    return render(request, 'core/speaker_detail.html', context)

def talk_list(request):
    return render(request, 'core/talk_list.html')

def talk_list(request):
    context = {
               'morning_talks': Talk.objects.at_morning(),
               'afternoon_talks': Talk.objects.at_afternoon(),
               }
    return render(request, 'core/talk_list.html', context)

def talk_detail(request, pk):
    talk = get_object_or_404(Talk, pk=pk)
    context = {
               'talk': talk,
               }
    return render(request, 'core/talk_detail.html', context)

eventex/core/templates/base.html
<!doctype html>

{% load staticfiles %}
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html" charset="utf-8" />
  <meta name="description" content="EventeX" />
  <meta http-equiv='content-Language' content='en-US' />
  <link type="image/x-icon" href="{% static "favicon.ico" %}" rel="shortcut icon" />

  <title>EventeX</title>

  <link type="text/css" href="{% static "css/style.css" %}" rel="stylesheet" media="screen" />

  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.0/jquery.min.js"></script>
</head>
<body>
  <div id="page">
    <div id="header">
      <center>
        <img src="{% static "img/logo.png" %}" alt="EventeX" />
      </center>
    </div>
    <hr>
    <div id="content">
      {% block content %}
      {% endblock content%}
    </div>
    <hr>
    <div id="footer">
      <p>&copy; 2012. <a rel="license" href="http://eventex.herike.com">EventeX</a>, some rights reserved. <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/br/80x15.png" /></a><a href="http://www.djangoproject.com/" id="django"><img src="https://djangoproject.com/s/img/badges/djangosite100x25.gif" border="0" alt="A Django site." title="A Django site." /></a></p>
    </div>
  </div>
</body>
</html>

eventex/core/templates/index.html
{% extends 'base.html' %}
{% block content %}
      <h1>Bem-vindo ao EventeX!</h1>
      <p>O evento mais sensacional do ano depois do Dev in Rio!</p>
      <p>Você não pode perder esta oportunidade!</p>
	  <p><strong><a href="{% url 'subscriptions:subscribe' %}">Inscreva-se já!</a></strong></p>      
      <p>Para dúvidas e mais informações entre em contato com <a href="mailto:eventex@eventex.com.br">eventex@eventex.com.br</a></p>
{% endblock content %}